-- Create incidents table
CREATE TABLE public.incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    time TEXT NOT NULL,
    time_elapsed TEXT,
    distance TEXT,
    description TEXT NOT NULL,
    risk TEXT NOT NULL,
    lat FLOAT NOT NULL,
    lng FLOAT NOT NULL,
    type TEXT NOT NULL,
    location TEXT NOT NULL,
    is_verified BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.incidents ENABLE ROW LEVEL SECURITY;

-- Create policy to allow anyone to read incidents (Public Read)
CREATE POLICY "Enable read access for all users"
ON public.incidents FOR SELECT
USING (true);

-- Insert dummy data into incidents
INSERT INTO public.incidents (id, title, time, time_elapsed, distance, description, risk, lat, lng, type, location, is_verified)
VALUES
(1, 'Potensi Begal Fatal', '02:14 AM', '10 mins ago', '1.2km dari Anda', 'AI mendeteksi anomali pergerakan sekelompok motor berhenti di area minim cahaya mencurigakan membawa senjata tajam.', 'TINGGI', 40, 35, 'Kriminal', 'Sudirman', false),
(2, 'Laporan Begal Berenjata', '03:30 AM', '45 mins ago', '3.5km dari Anda', 'Seseorang melaporkan pembegalan fatal dengan senjata tajam, pengambilan motor dan barang berharga korban.', 'TINGGI', 65, 60, 'Kriminal', 'Kuningan', true),
(3, 'Komplotan Meresahkan', '04:20 AM', '2 hours ago', '5.0km dari Anda', 'Kamera CCTV menangkap kawanan mencurigakan menggunakan senjata tajam melakukan penyisiran target begal.', 'SEDANG', 25, 70, 'Kriminal', 'Kemang', true);
