-- =========================================
-- USERS TABLE
-- =========================================
CREATE TABLE public.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username TEXT NOT NULL UNIQUE,
    avatar_url TEXT,
    role TEXT NOT NULL DEFAULT 'user',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

-- =========================================
-- NEWS TABLE
-- dashboard / berita / kasus
-- =========================================
CREATE TABLE public.news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    title TEXT NOT NULL,
    content TEXT NOT NULL,

    source_name TEXT,
    source_url TEXT,

    image_url TEXT,

    crime_type TEXT NOT NULL DEFAULT 'Begal',

    location_name TEXT NOT NULL,

    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,

    radius_meter INTEGER NOT NULL DEFAULT 300,

    risk_level TEXT NOT NULL DEFAULT 'Warning',

    verification_status TEXT NOT NULL DEFAULT 'Belum Terverifikasi',

    incident_at TIMESTAMP WITH TIME ZONE,
    published_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),

    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

-- =========================================
-- REPORTS TABLE
-- tombol lapor
-- =========================================
CREATE TABLE public.reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    description TEXT NOT NULL,

    incident_date DATE NOT NULL,
    incident_time TIME NOT NULL,

    location_name TEXT NOT NULL,

    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,

    image_url TEXT,

    report_status TEXT NOT NULL DEFAULT 'Belum Terverifikasi',

    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL,

    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE
);

-- =========================================
-- ENABLE ROW LEVEL SECURITY
-- =========================================
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

-- =========================================
-- PUBLIC READ POLICY (NEWS)
-- semua orang bisa baca berita/kasus
-- =========================================
CREATE POLICY "Public read access for news"
ON public.news
FOR SELECT
USING (true);

-- =========================================
-- PUBLIC INSERT POLICY (REPORTS)
-- semua user bisa kirim laporan
-- =========================================
CREATE POLICY "Public insert access for reports"
ON public.reports
FOR INSERT
WITH CHECK (true);

-- =========================================
-- USER READ OWN REPORTS
-- =========================================
CREATE POLICY "Users can read own reports"
ON public.reports
FOR SELECT
USING (auth.uid() = user_id);

-- =========================================
-- USER UPDATE OWN REPORTS
-- =========================================
CREATE POLICY "Users can update own reports"
ON public.reports
FOR UPDATE
USING (auth.uid() = user_id);

CREATE POLICY "Users can read own profile"
ON public.users
FOR SELECT
USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile"
ON public.users
FOR INSERT
WITH CHECK (auth.uid() = id);

-- =========================================
-- DUMMY DATA NEWS
-- =========================================
INSERT INTO public.news (
    title,
    content,
    source_name,
    source_url,
    image_url,
    crime_type,
    location_name,
    latitude,
    longitude,
    radius_meter,
    risk_level,
    verification_status,
    incident_at
)
VALUES
(
    'Aksi Begal di Tanah Abang',
    'Dilaporkan telah terjadi perampasan motor dan kekerasan oleh sekelompok begal bersenjata di kawasan Tanah Abang.',
    'Radar Begal',
    'https://radarbegal.id',
    'https://images.unsplash.com/photo-1502877338535-766e1452684a',
    'Begal',
    'Tanah Abang, Jakarta Pusat',
    -6.1874,
    106.8166,
    300,
    'CRITICAL',
    'Terverifikasi',
    timezone('utc', now())
),
(
    'Aksi Begal Motor di Tanah Abang',
    'Warga melaporkan aksi Begal, terhadap pengendara motor pada malam hari.',
    'Radar Begal',
    'https://radarbegal.id',
    'https://images.unsplash.com/photo-1517841905240-472988babdf9',
    'Jambret',
    'Kemang, Jakarta Selatan',
    -6.2615,
    106.8106,
    250,
    'WARNING',
    'Belum Terverifikasi',
    timezone('utc', now())
);

-- =========================================
-- DUMMY DATA REPORTS
-- =========================================
INSERT INTO public.reports (
    description,
    incident_date,
    incident_time,
    location_name,
    latitude,
    longitude,
    image_url,
    report_status
)
VALUES
(
    'Ada sekelompok motor mencurigakan berhenti di pinggir jalan.',
    CURRENT_DATE,
    CURRENT_TIME,
    'Sudirman, Jakarta',
    -6.2088,
    106.8456,
    'https://images.unsplash.com/photo-1517022812141-23620dba5c23',
    'Belum Terverifikasi'
);