ALTER TABLE public.berita_begal
ADD COLUMN IF NOT EXISTS lokasi TEXT NOT NULL DEFAULT 'Jakarta',
ADD COLUMN IF NOT EXISTS status_verifikasi TEXT NOT NULL DEFAULT 'Menunggu Validasi',
ADD COLUMN IF NOT EXISTS kategori TEXT NOT NULL DEFAULT 'Begal',
ADD COLUMN IF NOT EXISTS tingkat_risiko TEXT NOT NULL DEFAULT 'WATCH';
